# Generated by Django 5.1.1 on 2024-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
