# Generated by Django 5.1.1 on 2024-11-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_expense_notes_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Communication', 'Communication'), ('Childcare', 'Childcare'), ('Dining Out', 'Dining Out'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Gas', 'Gas'), ('Groceries', 'Groceries'), ('Housing', 'Housing'), ('Maintenance', 'Maintenance'), ('Medical', 'Medical'), ('Office Supplies', 'Office Supplies'), ('Personal Care', 'Personal Care'), ('Pets', 'Pets'), ('Recurring Expense', 'Recurring Expense'), ('Transportation', 'Transportation'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
